version: "3.5"

services:
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    ports:
      - "9200:9200"
    restart: "no"
    volumes:
      - data:/usr/share/elasticsearch/data

volumes:
  data:
