version: "3.5"

services:
  search:
    image: typesense/typesense:0.25.1
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: xyz
    ports:
      - "8108:8108"
    restart: "no"
    volumes:
      - data:/data

volumes:
  data:
